### ISSUE TITLE
how to get the newest information of the RL paper

### ISSUE THREAD

**Issue by 1576012404** [dbobrenko/reinforcement-learning-papernotes#1]
thank you! the recommended papers are all excellent. i want to know how i can get the the state of art paper in RL  if you do not tell me by this github repository.how to find RL paper by myself?

**Comment by dbobrenko** [comment]
Hey! You can check https://github.com/dbobrenko/reinforcement-learning-notes#miscellaneous section. 
But usually I search for new papers through my twitter feed, just subscribe to some famous researchers in Deep RL field.

**Comment by 1576012404** [comment]
ok, thank u!
